
apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekkyTWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1NjgxMDc0LCJpYXQiOjE3NzU2Nzc0NzQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYWNjM2FlZjAtM2I1OS00Yzc0LWFjZjktYTliNGRlOWY0MDE5Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjIwMmM4NjJmLTFmYTQtNDY3Mi1hMDlhLWQyODRlMWQ0OTUxYyJ9fSwibmJmIjoxNzc1Njc3NDc0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.J7nGNOFloEJ8_Fh-ILmgneR1fwib0CFej1XwzFvuIqJJRk0wFPrg6B-uMFz6CSVRaSABztfTTarse_jZFtBTqDjAqTKVmOw-qwgeRWDW1M0EL_txJaNhw0rK89Pj9Abc8k9X3_NvAbyPy1XANMB-xmVILJYr1aCYQJFfTrz6wIqW1ILOiD2rh5Px1hqCwBGzGJRfAh1FNzrnS7WjKFHoDHPIDToeWkUrCSWSZE8jANa9ltMWoSuR3bPmXDNKqli04gJV40-D2QBtf1vgsQPW4klF6ETHfda2VLS44yqO0B0AsLmpGg3iQfFp5PmZ_1seAW_LDqUifvtdtyRwYL-okA

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
